### ISSUE TITLE
Path

### ISSUE THREAD

**Issue by jayanthsv** [alvistack/ansible-role-perforce#1]
Would be a good addition to update $PATH with /opt/perforce/bin and source ~/.bashrc.

**Comment by hswong3i** [comment]
@jayanthsv why `/opt/perforce/bin` is required? Molecule test cases show it is working fine without it in `$PATH`, see:
* https://github.com/alvistack/ansible-role-perforce/blob/master/molecule/default/verify.yml
* https://gitlab.com/alvistack/ansible-role-perforce/-/jobs/1256220547#L301
